Fix Rendered Sound. Co Authored by: @Manongjohn
opentoonz/opentoonz pull request #4409
Opened 2022-04-25 17:39 UTC by JPUser1

2022-04-25 18:29 UTC, manongjohn commented
Still not doing the co-authored by correctly, but at least the PR doesn't have extra stuff in it anymore.

2022-04-25 18:31 UTC, JPUser1 commented
> 
so sorry I will get I will try to get it right still new with Github.

2022-04-25 22:00 UTC, RodneyBaker commented
Testing this port now.  

REF:  https://github.com/tahoma2d/tahoma2d/pull/981

2022-04-26 01:08 UTC, konero commented
Some pointers.

- When writing a pull request, include a description of what the problem was and why this solves it.
- In GitHub Desktop, you can add co-authors this way in the commit message box.
<img src="https://user-images.githubusercontent.com/19820721/165197371-b0bc6817-ec5f-48fb-a96d-cb10ae68bf19.gif" width="300px">

You can delete the unnecessary whitespace character on line 84 and commit to this branch including manongjohn this time, I think the commit messages will get merged together (?).

2022-04-26 01:08 UTC, konero commented on toonz/sources/toonzlib/movierenderer.cpp
> +       TXshColumn *col         = xs->getColumn(k);
```suggestion
      TXshColumn *col         = xs->getColumn(k);
```

2022-04-26 03:28 UTC, manongjohn commented
@RodneyBaker @shun-iwasawa 

Please let this serve as a formal request that if any of my changes in T2D are ported to OT and I am not properly credited in the `commit` message, then I ask that you do not merge it until the submitter fixes it **correctly**.

This ensures my contributions are properly recorded in the commit history. Crediting in the PR title/body is not the same thing as the repo can be moved and disassociated from the PRs but the commit history will always contain the original authors.

I ensure anything I port from OT to T2D is properly credited.  I expect the same consideration.

2022-04-26 03:53 UTC, shun-iwasawa requested changes
@JPUser1 Please try the following:

- Move to the working branch.

`> git checkout OpenToonz-Fix-rendered-sound-starting-too-soon`

- Start modifying the last commit message.

`> git commit --amend`

- Change the commit message, adding "Co-authored-by" like as follows:
```
Update movierenderer.cpp

Co-authored-by: manongjohn <dancel@ptd.net>
```
- Push the working branch again (with force push option).

`> git push -f origin OpenToonz-Fix-rendered-sound-starting-too-soon`

2022-04-26 03:58 UTC, manongjohn commented
Please use: `manongjohn <19245851+manongjohn@users.noreply.github.com>`

2022-04-26 04:01 UTC, shun-iwasawa commented
@manongjohn Modified the post. Thanks!

2022-04-26 04:01 UTC, JPUser1 commented
ok.

2022-04-26 04:03 UTC, closed without merging